#!/bin/sh
# vim: ft=sh ts=4 sw=4 sts=4 noet

captain_hindsight() {
	# shellcheck disable=SC2181
	[ $? -ne 0 ] || return 0           # Exit status code was 0
	[ -n "$*" ] || return 0            # Exit if the cmdline was empty
	[ ! -f /tmp/fatality ] || return 0 # Exit if the failure was generated by fatality and thus already has a message
	cmdline="dab $*"

	echo
	error "I'm sorry, it looks like the command '$cmdline' failed."

	case "$cmdline" in
	'dab apps'*)
		error "If the app is misbehaving perhaps try 'dab apps update <APP_NAME>' and start it up again"
		error "If you are unsure what the app is doing try 'dab apps logs <APP_NAME>'"
		error "If the app has some bad data perhaps try 'dab apps destroy <APP_NAME>' and start it up again"
		;;
	'dab pki issue'* | 'dab pki renew'*)
		error "If the pki is misbehaving perhaps try 'dab pki ready'"
		error "If the pki has some bad data perhaps try 'dab pki destroy'"
		;;
	'dab pki ready'* | 'dab pki up'*)
		error "If the pki has some bad data perhaps try 'dab pki destroy'"
		;;
	'dab config'*)
		error "If the config key needs to be wiped, then give no value to 'dab config set'"
		;;
	'dab network proxy'*)
		error "To fix mitmproxy certificates you may try 'dab pki destroy' to wipe them"
		error "If mitmproxy is having trouble starting, check its logs with 'dab apps logs mitmproxy'"
		;;
	esac

	error 'If you believe this to due to a problem with Dab please file a bug report at https://github.com/Nekroze/dab/issues/new?template=bug_report.md or come have a chat with the good folks at https://gitter.im/developer-lab who are eager to help'
}
