#!/bin/sh
# Description: Displays the address of any services exposed by the service
# Usage: <TOOL_NAME>
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1091
. ./lib/docker.sh
# shellcheck disable=SC1091
. ./lib/output.sh

[ -n "${1:-}" ] || fatality 'must provide a service name'
service="$1"

[ -n "$(dpose services top "$service")" ] || fatality "$service is not running"

id="$(compose_service_to_id services "$service")"
inform "$(container_id_to_url "$id")"
