#!/bin/sh
# Description: Display the docker-compose config for a service
# Usage: <SERVICE_NAME>
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1091
. ./lib/docker.sh

[ -n "${1:-}" ] || fatality 'must provide a service name'

compose_service_config "$1"
