#!/bin/sh
# Description: Start the container for a given service, or all services if none is given
# Usage: [<TOOL_NAME>]
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1091
. ./lib/docker.sh
# shellcheck disable=SC1091
. ./lib/output.sh

dpose services up -d "$@"

service="${1:-}"
# If there was no service (eg when starting all) stop here
[ -z "$service" ] && exit 0

dab services address "$service"
