#!/bin/sh
# Description: Update the image for the given service, or all services if none is given
# Usage: [<TOOL_NAME>]
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1091
. ./lib/docker.sh

dpose services pull --include-deps "$@"
dpose services build --parallel --pull --force-rm "$@"
