sudo: required

language: nix

services:
  - docker


git:
  quiet: true

stages:
  - Danger
  - Tests
  - Nix

jobs:
  include:

    - stage: Danger
      name: Danger Checks
      script:
        - yarn install
        - yarn danger ci

    - stage: Tests
      name: Behaviour Tests
      script: ./scripts/test.sh

    - stage: Nix
      name: Nix Package
      script: nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}'
