sudo: required

language: nix

git:
  quiet: true

stages:
  - Danger
  - Nix

jobs:
  include:

    - stage: Danger
      name: Danger Checks
      script: ./scripts/danger.sh
      cache: yarn

    - stage: Nix
      name: Nix Package
      script: nix-build -E 'with import <nixpkgs> {}; callPackage ./default.nix {}'
