#!/bin/sh
# Description: Recreate the lab network and its tooling
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -eu

# shellcheck source=app/lib/docker.sh
. "$DAB/lib/docker.sh"

containers_on_network() {
	docker ps --filter "network=$1" -q
}

action_containers_on_network() {
	containers="$1"
	network="$2"
	action="${3:-connect}"
	for container in $containers; do
		quietly docker network "$action" "$network" "$container"
	done
}

lab_network='lab'
app_network='dab_default'

lab_containers="$(containers_on_network "$lab_network")"
apps_containers="$(containers_on_network "$app_network")"

action_containers_on_network "$lab_containers" "$lab_network" disconnect
action_containers_on_network "$apps_containers" "$app_network" disconnect

dpose shell down --volumes
dpose shell up --no-start

action_containers_on_network "$lab_containers" "$lab_network" connect
action_containers_on_network "$apps_containers" "$app_network" connect
