#!/bin/sh
# Description: Displays the addresses of any exposed/published ports
# Usage: <APP_NAME>
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -eu

# shellcheck source=app/lib/docker.sh
. "$DAB/lib/docker.sh"

[ -n "${1:-}" ] || fatality 'must provide an app name'
app="$1"

msgfmt="${COLOR_CYAN}$app is available at ${COLOR_BLUE}%s${COLOR_NC}\\n"
get_app_urls "$app" | xargs --no-run-if-empty printf "$msgfmt"
