#!/bin/sh
# Description: Displays the address of any apps exposed by the app
# Usage: <APP_NAME>
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1090
. "$DAB/lib/docker.sh"
# shellcheck disable=SC1090
. "$DAB/lib/output.sh"

[ -n "${1:-}" ] || fatality 'must provide an app name'
app="$1"

msgfmt="${COLOR_CYAN}$app is available at ${COLOR_BLUE}%s${COLOR_NC}\\n"
get_app_urls "$app" | xargs --no-run-if-empty printf "$msgfmt"
