#!/bin/sh
# Description: Displays the address of any apps exposed by the app
# Usage: <APP_NAME>
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1091
. ./lib/docker.sh
# shellcheck disable=SC1091
. ./lib/output.sh

[ -n "${1:-}" ] || fatality 'must provide a app name'
app="$1"

msgfmt="${COLOR_CYAN}$app is available at ${COLOR_BLUE}%s${COLOR_NC}\\n"
compose_service_to_urls apps "$app" | xargs --no-run-if-empty printf "$msgfmt"
