#!/bin/sh
# Description: Display the docker-compose config for a app
# Usage: <APP_NAME>
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -eu

# shellcheck source=app/lib/docker.sh
. "$DAB/lib/docker.sh"

[ -n "${1:-}" ] || fatality 'must provide an app name'

highlight \
	--syntax yaml \
	-O xterm256 \
	"$DAB/docker/docker-compose.$1.yml"
