#!/bin/sh
# Description: Display the docker-compose config for a app
# Usage: <APP_NAME>
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1090
. "$DAB/lib/docker.sh"

[ -n "${1:-}" ] || fatality 'must provide an app name'

compose_app_config "$1"
