#!/bin/sh
# Description: Display the docker-compose config for a app
# Usage: <APP_NAME>
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1091
. ./lib/docker.sh

[ -n "${1:-}" ] || fatality 'must provide a app name'

compose_service_config apps "$1"
