#!/bin/sh
# Description: Destroy containers and volumes for one or all apps if none is specified.
# Usage: [<APP_NAME>]
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -eu

# shellcheck source=app/lib/docker.sh
. "$DAB/lib/docker.sh"

if [ -n "${1:-}" ]; then
	dpose "$1" down --volumes
elif query_user "Are you sure you would like to destroy data and containers for all apps?"; then
	dpose_all down --volumes
fi
