#!/bin/sh
# Description: Destroy containers and volumes for a specific (or all if none given) app
# Usage: [<APP_NAME>]
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1091
. ./lib/docker.sh
# shellcheck disable=SC1091
. ./lib/output.sh

if [ -n "${1:-}" ]; then
	dpose apps rm --stop -v -f "$@"
	carelessly docker volume rm "dab_$1"
else
	dpose apps down --volumes
fi
