#!/bin/sh
# Description: Run a command in the running instance of the given app
# Usage: <APP_NAME> <CMD>...
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1091
. ./lib/docker.sh
# shellcheck disable=SC1091
. ./lib/output.sh

[ -n "${1:-}" ] || fatality 'must provide a app name'
app="$1"
shift

dpose apps exec "$app" "$@"
