#!/bin/sh
# Description: Run a command in the running instance of the given app
# Usage: <APP_NAME> [<CMD>...]
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -eu

# shellcheck source=app/lib/docker.sh
. "$DAB/lib/docker.sh"

[ -n "${1:-}" ] || fatality 'must provide an app name'
app="$1"
shift

dpose "$app" exec "$app" "${@:-/bin/sh}"
