#!/bin/sh
# Description: Open a shell in a temporary instance of the given app
# Usage: <APP_NAME>
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1090
. "$DAB/lib/docker.sh"
# shellcheck disable=SC1090
. "$DAB/lib/output.sh"

[ -n "${1:-}" ] || fatality 'must provide an app name'
app="$1"
shift

dpose "$app" run --entrypoint /bin/sh --rm "$app"
