#!/bin/sh
# Description: List available apps
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1090
. "$DAB/lib/docker.sh"

compose_to_services_data apps | column -s'`' -o' | ' -t -N NAME,DESCRIPTION,USERNAME,PASSWORD -R NAME
