#!/bin/sh
# Description: Display logs for one or more apps
# Usage: <APP_NAME>...
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -eu

# shellcheck source=app/lib/docker.sh
. "$DAB/lib/docker.sh"

[ -n "${1:-}" ] || fatality 'must provide at least one app name'
dpose "$1" logs -f "$@"
