#!/bin/sh
# Description: Restart the running instance of the given app
# Usage: <APP_NAME>
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -eu

# shellcheck source=app/lib/docker.sh
. "$DAB/lib/docker.sh"

[ -n "${1:-}" ] || fatality 'must provide an app name'

dpose "$1" restart "$1"
