#!/bin/sh
# Description: Run a command in a new instance of given app's container
# Usage: <APP_NAME> [<CMD>...]
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -eu

# shellcheck source=app/lib/docker.sh
. "$DAB/lib/docker.sh"

[ -n "${1:-}" ] || fatality 'must provide an app name'
dpose "$1" run --rm "$@"
