#!/bin/sh
# Description: Start the container for a given app, or all apps if none is given
# Usage: [<APP_NAME>]
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1090
. "$DAB/lib/docker.sh"
# shellcheck disable=SC1090
. "$DAB/lib/output.sh"

dpose apps up -d "$@"

app="${1:-}"
# If there was no app (eg when starting all) stop here
[ -z "$app" ] && exit 0

dab apps address "$app"
