#!/bin/sh
# Description: Start the container(s) for the given app
# Usage: <APP_NAME>
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -eu

# shellcheck source=app/lib/docker.sh
. "$DAB/lib/docker.sh"

[ -n "${1:-}" ] || fatality 'must provide an app name'
app=$1
shift

dpose "$app" up --detach "$@"
dab apps address "$app" | grep ':3\d*' || true
