#!/bin/sh
# Description: Display the status of the given app, or all apps if none is given
# Usage: [<APP_NAME>]
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1090
. "$DAB/lib/docker.sh"

dpose apps ps "$@"
