#!/bin/sh
# Description: Stop the container(s) for the given app(s), or all apps if none is given
# Usage: <APP_NAME>...
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -eu

# shellcheck source=app/lib/docker.sh
. "$DAB/lib/docker.sh"

[ -n "${1:-}" ] || fatality 'must provide an app name'
dpose_all stop --timeout 30 "$@"
