#!/bin/sh
# Description: Update the image for the given app, or all apps if none is given
# Usage: [<APP_NAME>]
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1091
. ./lib/docker.sh

dpose apps pull --include-deps "$@" || true
dpose apps build --parallel --pull --force-rm "$@"
