#!/bin/sh
# Description: Update the image for the given app
# Usage: <APP_NAME>
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1090
. "$DAB/lib/docker.sh"

[ -n "${1:-}" ] || fatality 'must provide an app name'
app="$1"
shift
dpose "$app" pull --include-deps "$@" || true
dpose "$app" build --parallel --pull --force-rm "$@"
