#!/bin/sh
# Description: Destroy the vault's persistent storage and reset the pki
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

dab apps destroy vault || true
dab apps destroy consul || true
dab config set pki
