#!/bin/sh
# Description: Clone a known repo (or list of them) by name
# Usage: <REPO_NAME>...
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1090
. "$DAB/lib/config.sh"

[ -n "${1:-}" ] || fatality 'must provide at least one repo name paramater'

for repo in "$@"; do
	url="$(config_get "repo/$repo/url")"
	[ -n "$url" ] || fatality "url for repo $repo is unknown"

	[ -d "$DAB_REPO_PATH/$repo" ] || git clone --recursive "$url" "$DAB_REPO_PATH/$repo"

	if [ -d "$DAB_CONF_PATH/repo/$repo/remotes/" ]; then
		cd "$DAB_REPO_PATH/$repo"
		# shellcheck disable=SC2044
		for remkey in $(find "$DAB_CONF_PATH/repo/$repo/remotes/" -type f -maxdepth 1); do
			[ ! -d "$remkey" ] || continue
			remname="$(basename "$remkey")"
			remurl="$(config_get "repo/$repo/remotes/$remname")"
			inform "configuring $repo remote $remname to $remurl"
			if git remote | grep -qE "^$remname$"; then
				git remote set-url "$remname" "$remurl"
			else
				git remote add "$remname" "$remurl"
			fi
		done
	fi
done
