#!/bin/sh
# Description: Clone a known repo (or list of them) by name
# Usage: <REPO_NAME>...
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1090
. "$DAB/lib/config.sh"

[ -n "${1:-}" ] || fatality 'must provide at least one repo name paramater'

for repo in "$@"; do
	url="$(config_get "repo/$repo/url")"
	[ -n "$url" ] || fatality "url for repo $repo is unknown"
	repopath="$DAB_REPO_PATH/$repo"
	[ ! -d "$repopath" ] || return 0

	mkdir -p "$DAB_REPO_PATH"
	git clone "$url" "$repopath"
done
