#!/bin/sh
# Description: Fetch all repos to check for available updates
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -eu

# shellcheck source=app/lib/update.sh
. "$DAB/lib/update.sh"

START_PATH="$PWD"
for repo in "$DAB_CONF_PATH/repo/"*; do
	name="$(basename "$repo" | sed "s@^$DAB_CONF_PATH@@")"
	if [ -d "$DAB_REPO_PATH/$name" ]; then
		inform "checking $name repo for updates"
		cd "$DAB_REPO_PATH/$name"
		if git fetch | silently grep origin/master; then
			inform "$name repo has updates on origin/master!"
		fi
	fi
done
cd "$START_PATH"
