#!/bin/sh
# Description: List all repositories
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1090
. "$DAB/lib/update.sh"

dab repo fetch

repo_data=''
repo_row() {
	repo_data="$repo_data
$1:$2:$3"
}

set +f
for dir in "$DAB_CONF_PATH"/repo/*; do
	repo="$(basename "$dir")"

	status='not downloaded'
	[ -d "$DAB_REPO_PATH/$repo" ] && status='downloaded'

	uptodate=''
	if [ "$status" != 'not downloaded' ]; then
		if check_repo_is_up_to_date "$repo"; then
			uptodate='✓'
		else
			uptodate='✗'
		fi
	fi

	repo_row "$repo" "$status" "${uptodate:-}"
done
set -f

echo "$repo_data" | column -s':' -o' | ' -t -N REPO,STATUS,UPTODATE -R status
