#!/bin/sh
# Description: List all defined repositories
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -eu

repo_data=''
repo_row() {
	repo_data="$repo_data
$1\`$2\`$3"
}

# shellcheck disable=SC2125
repos=$(ls "$DAB_CONF_PATH/repo/")

for repo in $repos; do
	[ -f "$DAB_CONF_PATH/repo/$repo/url" ] || continue
	status='not cloned'
	[ -d "$DAB_REPO_PATH/$repo" ] && status='cloned'

	site="$(dab config get repo/"$repo"/website)"

	repo_row "$repo" "$status" "$site"
done

printf '%b\n' "$(echo "$repo_data" | column -s'\`' -o' │ ' -t -N REPO,STATUS,SITE -R status | colorize_stdin_glyphs)"
