#!/bin/sh
# Description: Add to (or create a new) group the given group as a dependency
# Usage: <GROUP_NAME> <GROUP_NAME>
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -eu

# shellcheck source=app/lib/config.sh
. "$DAB/lib/config.sh"

[ -n "${1:-}" ] || fatality 'must provide a group name to add too'
[ -n "${2:-}" ] || fatality 'must provide a group name to add as a dependency'
config_add "group/$1/groups" "$2"
