#!/bin/sh
# Description: Start a group's dependenant groups, then repo entrypoints, in FIFO order
# Usage: <GROUP_NAME>
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -eu

[ -n "${1:-}" ] || fatality 'must provide a group name to add too'
group_name="$1"
shift
run_with_dependencies() {
	depcmd="$1"
	configkey="$2"
	shift 2
	configpath="$(config_path "$configkey")"
	[ -f "$configpath" ] || return 0
	xargs -I{} sh -c "$depcmd {} $*" <"$configpath"
}

run_with_dependencies 'dab group start' "group/$group_name/groups"
run_with_dependencies 'dab repo entrypoint run' "group/$group_name/repos" "$@"
