#!/bin/sh
# Description: Displays the address of any tools exposed by the tool
# Usage: <TOOL_NAME>
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1091
. ./lib/docker.sh
# shellcheck disable=SC1091
. ./lib/output.sh

[ -n "${1:-}" ] || fatality 'must provide a tool name'
tool="$1"

[ -n "$(dpose tools top "$tool")" ] || fatality "$tool is not running"

id="$(compose_service_to_id tools "$tool")"
inform "$(container_id_to_url "$id")"
