#!/bin/sh
# Description: Displays the address of any tools exposed by the tool
# Usage: <TOOL_NAME>
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1091
. ./lib/docker.sh
# shellcheck disable=SC1091
. ./lib/output.sh

[ -n "${1:-}" ] || fatality 'must provide a tool name'
tool="$1"

msgfmt="${COLOR_CYAN}$tool is available at ${COLOR_BLUE}%s${COLOR_NC}\\n"
compose_service_to_urls tools "$tool" | xargs printf "$msgfmt"
