#!/bin/sh
# Description: Start the container for a given tool, or all tools if none is given
# Usage: [<TOOL_NAME>]
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1091
. ./lib/docker.sh
# shellcheck disable=SC1091
. ./lib/output.sh

dpose tools up -d "$@"

tool="${1:-}"
# If there was no tool (eg when starting all) stop here
[ -z "$tool" ] && exit 0

id="$(compose_service_to_id tools "$tool")"
url="$(container_id_to_url "$id")"
[ -z "$url" ] || inform "$tool is available at ${COLOR_BLUE}$url${COLOR_NC}"
