#!/bin/sh
# Description: Update the image for the given tool, or all tools if none is given
# Usage: [<TOOL_NAME>]
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1091
. ./lib/docker.sh

dpose tools pull --include-deps "$@" || true
dpose tools build --parallel --pull --force-rm "$@"
