#!/bin/sh
# Description: Add a value to a list config key
# Usage: <KEY> <VALUE>
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -eu

# shellcheck source=app/lib/config.sh
. "$DAB/lib/config.sh"

[ -n "${1:-}" ] || fatality 'must provide a config key'
key="$1"
shift

config_add "$key" "$@"
