#!/bin/sh
# Description: View all set config keys as a tree branching at a / in each key
# Usage: [<KEY>]
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -eu

# shellcheck source=app/lib/config.sh
. "$DAB/lib/config.sh"

path="$(config_path "${1:-}")"

[ -d "$path" ] || fatality 'Provided config key is not a namespace or does not exist'

cd "$path"
# Remove first, last, and empty lines from tree output
tree | sed \
	-e '1 d' \
	-e '$ d' \
	-e '/^\s*$/d'
