#!/bin/sh
# Description: Create an entrypoint (defaults to start) for the given repo
# Usage: <REPO_NAME> [<ENTRYPOINT_NAME>]
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1090
. "$DAB/lib/config.sh"

[ -n "${1:-}" ] || fatality 'must provide a repo name'
newpath="repo/$1/entrypoint/${2:-start}"

if [ ! -e "$DAB_CONF_PATH/$newpath" ]; then
	config_set "$newpath" "$(cat "$DAB/default-entrypoint.sh")"
	config_chmod "$newpath" +x
	inform 'This script will be executed with the root of the repository as the current working directory'
fi
