#!/bin/sh
# Description: List all entrypoints defined for the given repo
# Usage: <REPO_NAME>
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -eu

[ -n "${1:-}" ] || fatality 'must provide a repo name'

recklessly dab config tree "repo/$1/entrypoint"
recklessly dab config tree "repo/*/entrypoint"
