#!/bin/sh
# Description: List all entrypoints defined for the given repo
# Usage: <REPO_NAME>
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

[ -n "${1:-}" ] || fatality 'must provide a repo name'

# shellcheck disable=SC1090
. "$DAB/lib/config.sh"

carelessly dab config tree "repo/$1/entrypoint"
