#!/bin/sh
# Description: Execute an entrypoint for the given repo
# Usage: <REPO_NAME> <ENTRYPOINT_NAME>
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -eu

[ -n "${1:-}" ] || fatality 'must provide a repo name'
[ -n "${2:-}" ] || fatality 'must provide a entrypoint name'
repo="$1"
entry="$2"
shift
[ -n "${1:-}" ] && shift

dab repo clone "$repo"
suffix="$*"
[ -n "$suffix" ] && suffix=" $suffix"
inform "Executing $repo entrypoint $entry$suffix"

export DAB_CURRENT_REPO=$repo

entrypoint="$DAB_CONF_PATH/repo/$repo/entrypoint/$entry"
if [ ! -x "$entrypoint" ]; then
	entrypoint="$DAB_CONF_PATH/repo/*/entrypoint/$entry"
	if [ ! -x "$entrypoint" ]; then
		warn "$entry is not an executable entrypoint shell script for $repo"
		warn "You could write one to \$DAB_CONF_PATH/repo/$repo/entrypoint/$entry and make it executable with 'chmod +x'"
		exit 0
	fi
fi

cd "$DAB_REPO_PATH/$repo"
shellcheck --shell sh --color "$entrypoint" || true
env HOST_PWD="$DAB_REPO_PATH/$repo" \
	sh "$entrypoint" "$@"
