#!/bin/sh
# Description: Display the changelog as generated by git short logs, cut off at given revision
# Usage: [<COMPARISON_REVISION>]
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1091
. ./lib/output.sh

# If a revision is not given the initial commit is used as the floor
rev="${1:-2cd1ee8}"

# shellcheck disable=SC2039
echo -e "$(cat /LOG)" | sed "/$rev/q"
