#!/bin/sh
# Description: Install shell completion
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1090
. "$DAB/lib/update.sh"

maybe_update_completion
inform 'The shell completion binary has been placed in your home directory.'
inform 'To install shell completion please execute the following command:'
inform "$HOME/.dab-completion -install"
inform
inform 'Should this binary fail to work on your platform you can compile it like so:'
inform 'go get github.com/Nekroze/dab/completion'
inform 'completion -install'
