#!/bin/sh
# Description: Update dab
# vim: ft=sh ts=4 sw=4 sts=4 noet
set -euf

# shellcheck disable=SC1090
. "$DAB/lib/output.sh"
# shellcheck disable=SC1090
. "$DAB/lib/update.sh"

export self_update_period=10
maybe_selfupdate_dab
