FROM golang:latest AS build

ARG DIVE_VERSION=0.3.0
ENV PROJECT=github.com/wagoodman/dive
RUN go get -d -v "${PROJECT}/..." \
 && cd "$GOPATH/src/${PROJECT}" \
 && git checkout "v${DIVE_VERSION}" \
 && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
    -a -installsuffix cgo -ldflags='-w -s' -o /usr/bin/dive -v .

FROM scratch AS final
COPY --from=build /usr/bin/dive /dive
ENTRYPOINT ["/dive"]
