version: '3.5'

services:

  cyberchef:
    build:
      context: .
      dockerfile: Dockerfile.cyberchef
      args:
        - "NGINX_TAG=${DAB_TOOLS_NGINX_TAG:-alpine}"
    ports:
      - 80
    healthcheck:
      test: 'wget --spider http://localhost || exit 1'
      interval: 1m
      timeout: 10s
      retries: 3

  portainer:
    image: "portainer/portainer:${DAB_TOOLS_PORTAINER_TAG:-latest}"
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    ports:
      - 9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data

  tick:
    image: "chronograf:${DAB_TOOLS_CHRONOGRAF_TAG:-alpine}"
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    depends_on:
      - telegraf
      - influxdb
      - kapacitor
    networks:
      - default
      - observability
    volumes:
      - chronograf:/var/lib/chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    ports:
      - 8888
    links:
      - influxdb
      - kapacitor
    healthcheck:
      test: 'wget --spider http://localhost:8888/ || exit 1'
      interval: 1m
      timeout: 10s
      retries: 3

  telegraf:
    build:
      context: .
      dockerfile: Dockerfile.telegraf
      args:
        - "TELEGRAF_TAG=${DAB_TOOLS_TELEGRAF_TAG:-alpine}"
    depends_on:
      - influxdb
    networks:
      - default
      - observability
      - lab
    ports:
      - 8086
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/utmp:/var/run/utmp:ro
    healthcheck:
      test: 'wget --spider http://localhost:8086/ping || exit 1'
      interval: 1m
      timeout: 10s
      retries: 3

  influxdb:
    image: "influxdb:${DAB_TOOLS_INFLUXDB_TAG:-alpine}"
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    volumes:
      - influxdb:/var/lib/influxdb
    networks:
      - observability
    ports:
      - 8086
    healthcheck:
      test: 'wget --spider http://localhost:8086/ping || exit 1'
      interval: 1m
      timeout: 10s
      retries: 3

  kapacitor:
    image: "kapacitor:${DAB_TOOLS_KAPACITOR_TAG:-alpine}"
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    networks:
      - observability
    depends_on:
      - influxdb
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    links:
      - influxdb
    ports:
      - 9092
    volumes:
      - kapacitor:/var/lib/kapacitor
    healthcheck:
      test: 'wget --spider http://localhost:9092/kapacitor/v1/ping || exit 1'
      interval: 1m
      timeout: 10s
      retries: 3

  traefik:
    image: "traefik:${DAB_TOOLS_TRAEFIK_TAG:-alpine}"
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    command:
      - --ping
      - --web
      - --api
      - --docker
      - --accesslog
      - --tracing
      - --tracing.backend=zipkin
      - --tracing.zipkin
      - --tracing.zipkin.httpendpoint=http://telegraf:9411/api/v1/spans
    ports:
      - 80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - lab
      - default
      - observability
      - public
    healthcheck:
      test: 'wget --spider http://localhost:8080/ping || exit 1'
      interval: 1m
      timeout: 10s
      retries: 3

  ngrok:
    build:
      context: .
      dockerfile: Dockerfile.ngrok
    ports:
      - 4040
    depends_on:
      - traefik
    networks:
      - public
    healthcheck:
      test: 'wget --spider http://localhost:4040 || exit 1'
      interval: 1m
      timeout: 10s
      retries: 3

  logspout:
    image: "gliderlabs/logspout:${DAB_TOOLS_LOGSPOUT_TAG:-latest}"
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      syslog://telegraf:6514
    depends_on:
      - telegraf
    ports:
      - 80
    environment:
      INACTIVITY_TIMEOUT: 1m

  watchtower:
    image: v2tec/watchtower:latest
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --label-enable

  sysdig:
    image: "sysdig/sysdig:${DAB_TOOLS_SYSDIG_TAG:-latest}"
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /dev:/host/dev
      - /proc:/host/proc:ro
      - /boot:/host/boot:ro
      - /lib/modules:/host/lib/modules:ro
      - /usr:/host/usr:ro

  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
      args:
        - "GRAFANA_TAG=${DAB_TOOLS_GRAFANA_TAG:-latest}"
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    depends_on:
      - influxdb
    networks:
      - observability
    volumes:
      - grafana:/var/lib/grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
    ports:
      - 3000
    healthcheck:
      test: 'wget --spider http://localhost:3000/api || exit 1'
      interval: 1m
      timeout: 10s
      retries: 3

  consul:
    image: "consul:${DAB_TOOLS_CONSUL_TAG:-latest}"
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    networks:
      - observability
    volumes:
      - consul:/consul/data
    ports:
      - 8500
    environment:
      CONSUL_LOCAL_CONFIG: >
        {
          "datacenter": "${DAB_INSTANCE_NAME:-dab}",
          "skip_leave_on_interrupt": true,
          "addresses": {
            "http": "0.0.0.0",
            "dns": "0.0.0.0"
          }
        }
    command: agent -server -bootstrap -ui
    healthcheck:
      test: 'wget --spider http://localhost:8500/v1/status/leader || exit 1'
      interval: 1m
      timeout: 10s
      retries: 3

  serveo:
    build:
      context: .
      dockerfile: Dockerfile.ssh
    entrypoint:
      - /usr/bin/ssh
    command:
      - '-o StrictHostKeyChecking=no'
      - '-R 80:traefik:80'
      - 'serveo.net'
    networks:
      - public

  ntopng:
    build:
      context: .
      dockerfile: Dockerfile.ntopng
    network_mode: host
    ports:
      - 3000
    depends_on:
      - redis
    restart: on-failure
    command: --redis localhost:16379

  redis:
    image: "redis:${DAB_TOOLS_REDIS_TAG:-latest}"
    ports:
      - '16379:6379'

  vaultbot:
    image: "msvechla/vaultbot:${DAB_TOOLS_VAULTBOT_TAG:-latest}"
    entrypoint:
      - ./vaultbot
      - '--vault-adr=http://vault:8200'
    networks:
      - vault
    depends_on:
      - vault

  vault:
    build:
      context: .
      dockerfile: Dockerfile.vault
      args:
        - "VAULT_TAG=${DAB_TOOLS_VAULT_TAG:-latest}"
    restart: on-failure
    networks:
      vault:
      observability:
      lab:
        aliases:
          - vault
    healthcheck:
      test: 'wget --spider http://localhost:8200/v1/sys/health || exit 1'
      interval: 10s
      timeout: 9s
      retries: 3
    ports:
      - 8200
    environment:
      VAULT_ADDR: 'http://127.0.0.1:8200'
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul
      - telegraf

volumes:
  influxdb:
  kapacitor:
  chronograf:
  portainer:
  grafana:
  consul:
  vault:

networks:
  observability:
  public:
  vault:
  lab:
    external:
      name: lab

