version: '3.5'

services:

  memcached:
    container_name: dab_memcached
    image: "memcached:${DAB_APPS_MEMCACHED_TAG:-alpine}"
    labels:
      description: 'Distributed memory object caching'
      exposing: 'tcp'
      com.centurylinklabs.watchtower.enable: 'true'
    restart: on-failure
    tmpfs:
      - /tmp
    networks:
      - default
      - lab
    env_file:
      - /tmp/denvmux/memcached.env

networks:
  default:
    name: dab_apps
  lab:
    external:
      name: lab
