version: '3.5'

services:

  postgres:
    container_name: dab_postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
      args:
        - "POSTGRES_TAG=${DAB_APPS_POSTGRES_TAG:-latest}"
        - "LOCALE=${DAB_APPS_POSTGRES_LOCALE:-en_US}"
    labels:
      description: 'Object-relational database management system'
      exposing: 'tcp'
      com.centurylinklabs.watchtower.enable: 'true'
    restart: on-failure
    env_file:
      - /tmp/denvmux/postgres.env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
      - "$DAB_CONF_PATH/apps/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro"
    command: "${DAB_APPS_POSTGRES_FLAGS:-}"
    networks:
      - default
      - lab
    tmpfs:
      - /tmp

volumes:
  postgres:

networks:
  default:
    name: dab_apps
  lab:
    external:
      name: lab
