version: '3.5'

services:

  ballerina:
    container_name: dab_ballerina
    image: "ballerina/ballerina-platform:${DAB_APPS_BALLERINA_TAG:-latest}"
    labels:
      description: 'IDE and language designed to make integration simple.'
      com.centurylinklabs.watchtower.enable: 'true'
    restart: on-failure
    env_file:
      - /tmp/denvmux/ballerina.env
    network_mode: host
    command:
      - 'composer'
    ports:
      - '9091:9091'
    volumes:
      - "$DAB_REPO_PATH:$DAB_REPO_PATH"

networks:
  default:
    name: dab_apps
