version: '3.5'

services:

  sysdig:
    container_name: dab_sysdig
    image: "sysdig/sysdig:${DAB_APPS_SYSDIG_TAG:-latest}"
    labels:
      description: 'Universal system visibility tool'
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /dev:/host/dev
      - /proc:/host/proc:ro
      - /boot:/host/boot:ro
      - /lib/modules:/host/lib/modules:ro
      - /usr:/host/usr:ro
    env_file:
      - /tmp/denvmux/sysdig.env
    tmpfs:
      - /tmp

networks:
  default:
    name: dab_apps
