version: '3.5'

services:

  shell:
    container_name: dab_shell
    image: 'alpine:latest'
    labels:
      description: 'Simple shell attached to the lab docker network'
    networks:
      - lab
    env_file:
      - /tmp/denvmux/shell.env
    tmpfs:
      - /tmp

volumes:
  logs:

networks:
  lab:
    name: lab
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "${DAB_LAB_INTERNET:-false}"
    ipam:
      driver: default
      config:
        - subnet: "${DAB_LAB_SUBNET:-10.10.0.0/16}"
