version: '3.5'

services:

  influxdb:
    container_name: dab_influxdb
    image: "influxdb:${DAB_SERVICES_INFLUXDB_TAG:-alpine}"
    restart: on-failure
    labels:
      description: 'Time series database from the TICK stack'
      com.centurylinklabs.watchtower.enable: 'true'
    environment:
      INFLUXDB_DATA_QUERY_LOG_ENABLED: 'false'
      INFLUXDB_HTTP_LOG_ENABLED: 'false'
      INFLUXDB_HTTP_PPROF_ENABLED: 'false'
    volumes:
      - influxdb:/var/lib/influxdb
    healthcheck:
      test: 'wget --spider http://localhost:8086/ping || exit 1'
      interval: 30s
      timeout: 10s
      retries: 3
    tmpfs:
      - /tmp

  telegraf:
    container_name: dab_telegraf
    image: "telegraf:${DAB_SERVICES_TELEGRAF_TAG:-alpine}"
    labels:
      description: 'Metrics collection agent from the TICK stack'
    restart: on-failure
    command: --quiet
    environment:
      DAB_SERVICES_MYSQL_ROOT_PASSWORD: "${DAB_SERVICES_MYSQL_ROOT_PASSWORD:-root}"
    volumes:
      - gend:/etc/telegraf
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/utmp:/var/run/utmp:ro
    healthcheck:
      test: 'wget --spider http://localhost:8086/ping || exit 1'
      interval: 30s
      timeout: 10s
      retries: 3
    tmpfs:
      - /tmp

  logspout:
    container_name: dab_logspout
    image: "gliderlabs/logspout:${DAB_SERVICES_LOGSPOUT_TAG:-latest}"
    restart: on-failure
    labels:
      description: 'Log routing for Docker container logs, points to tick'
      com.centurylinklabs.watchtower.enable: 'true'
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      syslog://telegraf:6514
    environment:
      INACTIVITY_TIMEOUT: 1m
    tmpfs:
      - /tmp

  consul:
    container_name: dab_consul
    image: "consul:${DAB_SERVICES_CONSUL_TAG:-latest}"
    restart: on-failure
    labels:
      description: 'Services discovery and key value store'
      com.centurylinklabs.watchtower.enable: 'true'
    volumes:
      - consul:/consul/data
    ports:
      - 8500
    environment:
      CONSUL_LOCAL_CONFIG: >
        {
          "datacenter": "${DAB_INSTANCE_NAME:-dab}",
          "skip_leave_on_interrupt": true,
          "addresses": {
            "http": "0.0.0.0",
            "dns": "0.0.0.0"
          }
        }
    command: agent -server -bootstrap -ui
    healthcheck:
      test: 'wget --spider http://localhost:8500/v1/status/leader || exit 1'
      interval: 30s
      timeout: 10s
      retries: 3
    tmpfs:
      - /tmp

  redis:
    container_name: dab_redis
    image: "redis:${DAB_SERVICES_REDIS_TAG:-latest}"
    labels:
      description: 'In-memory data structure store'
      com.centurylinklabs.watchtower.enable: 'true'
    restart: on-failure
    healthcheck:
      test: 'redis-cli ping'
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - '16379:6379'
    tmpfs:
      - /tmp

  vault:
    container_name: dab_vault
    build:
      context: .
      dockerfile: Dockerfile.vault
      args:
        - "VAULT_TAG=${DAB_SERVICES_VAULT_TAG:-latest}"
    labels:
      description: 'Store, manage, and generate secrets with Hashicorp Vault``${DAB_SERVICES_VAULT_TOKEN:-}'
    restart: on-failure
    healthcheck:
      test: 'netstat -tulpn | grep 0.0.0.0:8200'
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      VAULT_ADDR: 'http://127.0.0.1:8200'
    cap_add:
      - IPC_LOCK
    tmpfs:
      - /tmp

  postgres:
    container_name: dab_postgres
    image: "postgres:${DAB_SERVICES_POSTGRES_TAG:-alpine}"
    labels:
      description: 'Object-relational database management system'
      com.centurylinklabs.watchtower.enable: 'true'
    restart: on-failure
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    tmpfs:
      - /tmp

  elasticsearch:
    container_name: dab_elasticsearch
    image: "docker.elastic.co/elasticsearch/elasticsearch:${DAB_SERVICES_ELASTICSEARCH_TAG:-6.4.2}"
    labels:
      description: 'Object-relational database management system'
    restart: on-failure
    environment:
      discovery.type: 'single-node'
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    healthcheck:
      test: 'curl -fsSL "http://localhost:9200/_cat/health?h=status" | grep green'
      interval: 30s
      timeout: 10s
      retries: 3
    tmpfs:
      - /tmp

  zookeeper:
    container_name: dab_zookeeper
    image: "confluentinc/cp-zookeeper:${DAB_SERVICES_ZOOKEEPER_TAG:-latest}"
    labels:
      description: 'Distributed configuration service'
      com.centurylinklabs.watchtower.enable: 'true'
    restart: on-failure
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: WARN
    tmpfs:
      - /tmp

  kafka:
    container_name: dab_kafka
    image: "confluentinc/cp-kafka:${DAB_SERVICES_KAFKA_TAG:-latest}"
    labels:
      description: 'Stream processing platform'
      com.centurylinklabs.watchtower.enable: 'true'
    restart: on-failure
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
    tmpfs:
      - /tmp

  mysql:
    container_name: dab_mysql
    image: "mysql:${DAB_SERVICES_MYSQL_TAG:-latest}"
    labels:
      description: "Open Source RDBMS`root`${DAB_SERVICES_MYSQL_ROOT_PASSWORD:-root}"
      com.centurylinklabs.watchtower.enable: 'true'
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: "${DAB_SERVICES_MYSQL_ROOT_PASSWORD:-root}"
    volumes:
      - mysql:/var/lib/mysql
    tmpfs:
      - /tmp

  nats:
    container_name: dab_nats
    image: "nats:${DAB_SERVICES_NATS_TAG:-latest}"
    labels:
      description: 'Cloud native messaging system'
      com.centurylinklabs.watchtower.enable: 'true'
    restart: on-failure
    tmpfs:
      - /tmp

  memcached:
    container_name: dab_memcached
    image: "memcached:${DAB_SERVICES_MEMCACHED_TAG:-alpine}"
    labels:
      description: 'Distributed memory object caching'
      com.centurylinklabs.watchtower.enable: 'true'
    restart: on-failure
    tmpfs:
      - /tmp

  docker-gen:
    container_name: dab_docker-gen
    build:
      context: .
      dockerfile: Dockerfile.docker-gen
      args:
        - "DOCKER_GEN_TAG=${DAB_SERVICES_DOCKER_GEN_TAG:-latest}"
    labels:
      description: 'Render files using live docker data'
      com.centurylinklabs.watchtower.enable: 'true'
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - gend:/srv/gend
    tmpfs:
      - /tmp

  remote-syslog2:
    container_name: dab_remote-syslog2
    build:
      context: .
      dockerfile: Dockerfile.remote_syslog2
    labels:
      description: 'Ingests .log files placed in the docker volume named dab_logs'
    restart: on-failure
    volumes:
      - logs:/srv/logs
    tmpfs:
      - /tmp

volumes:
  postgres:
  influxdb:
  grafana:
  consul:
  vault:
  mysql:
  gend:
  logs:
    external:
      name: dab_logs

networks:
  default:
    external:
      name: services
