FROM alpine:latest

RUN apk add --no-cache ca-certificates \
 && update-ca-certificates

ADD https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.tar.gz /ngrok.tar.gz

RUN tar -xf ngrok.tar.gz \
 && rm -f ngrok.tar.gz \
 && mv ngrok /bin/ngrok \
 && mkdir -p /root/.ngrok2 \
 && echo "web_addr: '0.0.0.0:4040'" > /root/.ngrok2/ngrok.yml

EXPOSE 4040
CMD /bin/ngrok http -log stdout "${HTTP_HOST:-traefik}:${HTTP_PORT:-80}"
