version: '3.5'

services:

  influxdb:
    image: "influxdb:${DAB_SERVICES_INFLUXDB_TAG:-alpine}"
    restart: on-failure
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    volumes:
      - influxdb:/var/lib/influxdb
    ports:
      - 8086
    healthcheck:
      test: 'wget --spider http://localhost:8086/ping || exit 1'
      interval: 30s
      timeout: 10s
      retries: 3
    tmpfs:
      - /tmp

  telegraf:
    build:
      context: .
      dockerfile: Dockerfile.telegraf
      args:
        - "TELEGRAF_TAG=${DAB_SERVICES_TELEGRAF_TAG:-alpine}"
    restart: on-failure
    depends_on:
      - influxdb
    ports:
      - 8086
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/utmp:/var/run/utmp:ro
    healthcheck:
      test: 'wget --spider http://localhost:8086/ping || exit 1'
      interval: 30s
      timeout: 10s
      retries: 3
    tmpfs:
      - /tmp

  logspout:
    image: "gliderlabs/logspout:${DAB_SERVICES_LOGSPOUT_TAG:-latest}"
    restart: on-failure
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      syslog://telegraf:6514
    depends_on:
      - telegraf
    ports:
      - 80
    environment:
      INACTIVITY_TIMEOUT: 1m
    tmpfs:
      - /tmp

  consul:
    image: "consul:${DAB_SERVICES_CONSUL_TAG:-latest}"
    restart: on-failure
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
    volumes:
      - consul:/consul/data
    ports:
      - 8500
    environment:
      CONSUL_LOCAL_CONFIG: >
        {
          "datacenter": "${DAB_INSTANCE_NAME:-dab}",
          "skip_leave_on_interrupt": true,
          "addresses": {
            "http": "0.0.0.0",
            "dns": "0.0.0.0"
          }
        }
    command: agent -server -bootstrap -ui
    healthcheck:
      test: 'wget --spider http://localhost:8500/v1/status/leader || exit 1'
      interval: 30s
      timeout: 10s
      retries: 3
    tmpfs:
      - /tmp

  redis:
    image: "redis:${DAB_SERVICES_REDIS_TAG:-latest}"
    restart: on-failure
    healthcheck:
      test: 'redis-cli ping'
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - '16379:6379'
    tmpfs:
      - /tmp

  vault:
    build:
      context: .
      dockerfile: Dockerfile.vault
      args:
        - "VAULT_TAG=${DAB_SERVICES_VAULT_TAG:-latest}"
    restart: on-failure
    healthcheck:
      test: 'vault status | grep Version'
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - 8200
    environment:
      VAULT_ADDR: 'http://127.0.0.1:8200'
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul
      - telegraf
    tmpfs:
      - /tmp

  postgres:
    image: "postgres:${DAB_SERVICES_POSTGRES_TAG:-alpine}"
    restart: on-failure
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    tmpfs:
      - /tmp

volumes:
  postgres:
  influxdb:
  grafana:
  consul:
  vault:

networks:
  default:
    external:
      name: services

