FROM golang:latest

RUN go mod init nekroze/dab/remote_syslog2 && \
 go get -d -v github.com/papertrail/remote_syslog2 && \
 go install github.com/papertrail/remote_syslog2

COPY configs/remote_syslog2.yml /etc/log_files.yml

ENTRYPOINT ["/go/bin/remote_syslog2","--no-detach"]
