version: '3.5'

services:

  cyberchef:
    build:
      context: .
      dockerfile: Dockerfile.cyberchef
      args:
        - "NGINX_TAG=${DAB_TOOLS_NGINX_TAG:-alpine}"
    labels:
      description: 'The Cyber Swiss Army Knife'
    ports:
      - 80
    healthcheck:
      test: 'wget --spider http://localhost || exit 1'
      interval: 1m
      timeout: 10s
      retries: 3
    tmpfs:
      - /tmp

  portainer:
    image: "portainer/portainer:${DAB_TOOLS_PORTAINER_TAG:-latest}"
    labels:
      description: 'Docker Management Web UI'
      com.centurylinklabs.watchtower.enable: 'true'
    ports:
      - 9000
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    tmpfs:
      - /tmp

  chronograf:
    image: "chronograf:${DAB_TOOLS_CHRONOGRAF_TAG:-alpine}"
    labels:
      description: 'Chronograf metrics explorer from the TICK stack'
      com.centurylinklabs.watchtower.enable: 'true'
    depends_on:
      - kapacitor
    networks:
      - services
    volumes:
      - chronograf:/var/lib/chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
      LOG_LEVEL: error
    ports:
      - 8888
    healthcheck:
      test: 'wget --spider http://localhost:8888/ || exit 1'
      interval: 1m
      timeout: 10s
      retries: 3
    tmpfs:
      - /tmp

  kapacitor:
    image: "kapacitor:${DAB_TOOLS_KAPACITOR_TAG:-alpine}"
    labels:
      description: 'Real-Time metrics processing from the TICK stack'
      com.centurylinklabs.watchtower.enable: 'true'
    networks:
      - services
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
      LOG_LEVEL: error
    ports:
      - 9092
    volumes:
      - kapacitor:/var/lib/kapacitor
    healthcheck:
      test: 'wget --spider http://localhost:9092/kapacitor/v1/ping || exit 1'
      interval: 1m
      timeout: 10s
      retries: 3
    tmpfs:
      - /tmp

  traefik:
    image: "traefik:${DAB_TOOLS_TRAEFIK_TAG:-alpine}"
    labels:
      description: 'The Cloud Native Edge Router, docker reverse proxy'
      com.centurylinklabs.watchtower.enable: 'true'
    command:
      - --ping
      - --web
      - --api
      - --docker
      - --accesslog
      - --tracing
      - --tracing.backend=zipkin
      - --tracing.zipkin
      - --tracing.zipkin.httpendpoint=http://telegraf:9411/api/v1/spans
    ports:
      - 80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - lab
      - default
      - services
      - public
    healthcheck:
      test: 'wget --spider http://localhost:8080/ping || exit 1'
      interval: 1m
      timeout: 10s
      retries: 3
    tmpfs:
      - /tmp

  ngrok:
    build:
      context: .
      dockerfile: Dockerfile.ngrok
    labels:
      description: 'Secure introspectable tunnels, points to traefik'
    ports:
      - 4040
    depends_on:
      - traefik
    networks:
      - public
    healthcheck:
      test: 'wget --spider http://localhost:4040 || exit 1'
      interval: 1m
      timeout: 10s
      retries: 3
    tmpfs:
      - /tmp

  watchtower:
    image: v2tec/watchtower:latest
    labels:
      description: 'Watches labelled container images for updates and applies them'
      com.centurylinklabs.watchtower.enable: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --label-enable
    tmpfs:
      - /tmp

  sysdig:
    image: "sysdig/sysdig:${DAB_TOOLS_SYSDIG_TAG:-latest}"
    labels:
      description: 'Universal system visibility tool with native support for containers'
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /dev:/host/dev
      - /proc:/host/proc:ro
      - /boot:/host/boot:ro
      - /lib/modules:/host/lib/modules:ro
      - /usr:/host/usr:ro
    tmpfs:
      - /tmp

  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
      args:
        - "GRAFANA_TAG=${DAB_TOOLS_GRAFANA_TAG:-latest}"
    labels:
      description: 'The open platform for analytics and monitoring`admin`admin'
      com.centurylinklabs.watchtower.enable: 'true'
    networks:
      - services
    volumes:
      - grafana:/var/lib/grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
    ports:
      - 3000
    healthcheck:
      test: 'wget --spider http://localhost:3000/api || exit 1'
      interval: 1m
      timeout: 10s
      retries: 3
    tmpfs:
      - /tmp

  serveo:
    build:
      context: .
      dockerfile: Dockerfile.ssh
    labels:
      description: 'Expose local servers to the internet'
    entrypoint:
      - /usr/bin/ssh
    command:
      - '-o StrictHostKeyChecking=no'
      - '-R 80:traefik:80'
      - 'serveo.net'
    networks:
      - public
    tmpfs:
      - /tmp

  ntopng:
    build:
      context: .
      dockerfile: Dockerfile.ntopng
    labels:
      description: 'Monitor network interfaces, requires redis service'
    network_mode: host
    ports:
      - 3000
    restart: on-failure
    command: --redis localhost:16379
    tmpfs:
      - /tmp

  vaultbot:
    image: "msvechla/vaultbot:${DAB_TOOLS_VAULTBOT_TAG:-latest}"
    labels:
      description: 'Automate interaction with Hashicorp Vault'
      com.centurylinklabs.watchtower.enable: 'true'
    entrypoint:
      - ./vaultbot
      - '--vault_addr=http://vault:8200'
    volumes:
      - "$DAB_CONF_PATH:$DAB_CONF_PATH"
    networks:
      - services
    tmpfs:
      - /tmp

  pgadmin:
    image: "dpage/pgadmin4:${DAB_TOOLS_PGADMIN_TAG:-latest}"
    labels:
      description: 'Postgres administration console`user@dab`admin'
      com.centurylinklabs.watchtower.enable: 'true'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'user@dab'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    networks:
      - services
      - lab
    ports:
      - 80
    tmpfs:
      - /tmp

  kafkacat:
    image: "confluentinc/cp-kafkacat:${DAB_TOOLS_KAFKACAT_TAG:-latest}"
    labels:
      description: 'Lightweight kafka console consumer/producer'
      com.centurylinklabs.watchtower.enable: 'true'
    networks:
      - services
      - lab
    entrypoint:
      - /usr/local/bin/kafkacat
    command: '-b kafka -L'

  adminer:
    image: "adminer:${DAB_TOOLS_ADMINER_TAG:-latest}"
    restart: on-failure
    labels:
      description: 'Database manager with a small footprint'
      com.centurylinklabs.watchtower.enable: 'true'
    networks:
      - services
      - lab
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080

  kibana:
    image: "kibana:${DAB_TOOLS_KIBANA_TAG:-6.4.2}"
    restart: on-failure
    labels:
      description: 'Explore and visualize elasticsearch data'
      com.centurylinklabs.watchtower.enable: 'true'
    networks:
      - services
    ports:
      - 5601

volumes:
  kapacitor:
  chronograf:
  portainer:
  grafana:

networks:
  public:
  services:
    external:
      name: services
  lab:
    external:
      name: lab
