version: '3.5'

services:

  postgres:
    container_name: dab_postgres
    image: "postgres:${DAB_APPS_POSTGRES_TAG:-alpine}"
    labels:
      description: 'Object-relational database management system'
      exposing: 'tcp'
      com.centurylinklabs.watchtower.enable: 'true'
    restart: on-failure
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    tmpfs:
      - /tmp

volumes:
  postgres:

networks:
  default:
    name: dab_apps
