version: '3.5'

services:

  watchtower:
    container_name: dab_watchtower
    image: v2tec/watchtower:latest
    restart: always
    labels:
      description: 'Watches labelled container images for updates and applies them'
      com.centurylinklabs.watchtower.enable: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --label-enable
    env_file:
      - /tmp/denvmux/watchtower.env
    tmpfs:
      - /tmp

networks:
  default:
    name: dab_apps
