version: '3.5'

services:

  kafka-topics-ui:
    container_name: dab_kafka-topics-ui
    image: "landoop/kafka-topics-ui:${DAB_APPS_KAFKA_TOPICS_UI_TAG:-latest}"
    labels:
      description: 'Web interface for inspecting Kafka topics'
      com.centurylinklabs.watchtower.enable: 'true'
    env_file:
      - /tmp/denvmux/kafka-topics-ui.env
    environment:
      KAFKA_REST_PROXY_URL: 'http://kafka-rest:8082'
      KAFKA_REST_BOOTSTRAP_SERVERS: "PLAINTEXT://${DAB_APPS_KAFKA_REST_TARGET_KAFKA:-kafka}:9092"
      PROXY: 'true'
    depends_on:
      - kafka
      - kafka-rest
    expose:
      - 8000
    ports:
      - 8000
    restart: on-failure
    tmpfs:
      - /tmp

networks:
  default:
    name: dab_apps
